repos:
  - repo: local
    hooks:

      - id: isort
        name: isort
        entry: isort --settings-path pyproject.toml .
        language: system
        types: [python]
        pass_filenames: false

      - id: black
        name: black
        entry: black --config pyproject.toml .
        language: system
        types: [python]
        pass_filenames: false
      
      - id: flake8
        name: flake8
        entry: flake8 --config pyproject.toml .
        language: system
        types: [python]
        pass_filenames: false

      # - id: mypy
      #   name: mypy
      #   entry: mypy --config pyproject.toml --namespace-packages .
      #   language: system
      #   types: [python]
      #   pass_filenames: false

      - id: pytest
        name: test
        entry: python -m pytest -s
        language: system
        pass_filenames: false
        always_run: true